on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx
      - uses: docker/login-action@v2
        name: Login to Github Container Registry
        with:
          registry: ghcr.io
          username: $
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        name: Build and push image
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: blechlawine/cluedo-app
