on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx
        with:
          platforms: linux/arm/v7
      - uses: docker/login-action@v2
        name: Login to Github Container Registry
        if: github.event_name == 'push'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        name: Set up Docker metadata
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository }}
      - uses: docker/build-push-action@v4
        name: Build and push image
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
